_default:
    @just --list

# Delete artifacts from work/
clean:
    rm work/*

# Test all components
test-all:
    @just test mux
    @just test adder
    @just test pc

# Test individual components: mux, adder
test component="component":
    @just _test-{{component}}

_test-mux:
    ghdl -a --std=08 --workdir=work src/mux.vhd
    ghdl -e --std=08 --workdir=work mux_tb
    ghdl -r --std=08 --workdir=work mux_tb --vcd=work/mux.vcd

_test-adder:
    ghdl -a --std=08 --workdir=work src/adder.vhd
    ghdl -e --std=08 --workdir=work adder_tb
    ghdl -r --std=08 --workdir=work adder_tb --vcd=work/adder.vcd

_test-pc:
    ghdl -a --std=08 --workdir=work src/pc.vhd
    ghdl -e --std=08 --workdir=work pc_register_tb
    ghdl -r --std=08 --workdir=work pc_register_tb --vcd=work/pc.vcd


